<a href="https://colab.research.google.com/github/heeboventure/Tensorflow/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/heeboventure/Tensorflow.git

Cloning into 'Tensorflow'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.


# 표를 다루는 도구 Pandas (판다스)

In [ ]:
import pandas as pd

In [ ]:
# 파일들로부터 데이터 읽어오기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스톤 = pd.read_csv(파일경로)

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [ ]:
# 데이터 모양으로 확인하기
print(레모네이드.shape)
print(보스톤.shape)
print(아이리스.shape)

(6, 2)
(506, 14)
(150, 5)


In [ ]:
# 칼럼 이름 출력
print(레모네이드.columns)
print(보스톤.columns)
print(아이리스.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [ ]:
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

독립 = 보스톤[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스톤[['medv']]
print(독립.shape, 종속.shape)

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


In [ ]:
# 상위 5개의 데이터만 출력
레모네이드.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
보스톤.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

# 레모네이드 판매 예측 (실습)

In [ ]:
# Loss = (예측 - 결과(종속변수))^2 의 평균

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
데이터 = pd.read_csv(파일경로)
데이터.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
# 종속변수, 독립변수
독립 = 데이터[['온도']]
종속 = 데이터[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [ ]:
# 모델을 만듭니다
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
# 모델을 학습합니다
model.fit(독립, 종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 1.4537e-04
Epoch 2/10
1/1 [==============================] - 0s 2ms/step - loss: 1.4530e-04
Epoch 3/10
1/1 [==============================] - 0s 1ms/step - loss: 1.4522e-04
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 1.4520e-04
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 1.4518e-04
Epoch 6/10
1/1 [==============================] - 0s 3ms/step - loss: 1.4516e-04
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 1.4522e-04
Epoch 8/10
1/1 [==============================] - 0s 3ms/step - loss: 1.4525e-04
Epoch 9/10
1/1 [==============================] - 0s 787us/step - loss: 1.4539e-04
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 1.4552e-04


In [ ]:
# 모델을 이용합니다
model.predict(독립)

array([[40.014416],
       [42.013428],
       [44.01244 ],
       [46.01145 ],
       [48.010464],
       [50.009476]], dtype=float32)

In [ ]:
model.predict([[15]])

array([[30.019354]], dtype=float32)

# 보스턴 집값 예측 (실습)

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
# 독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
# 3. 데이터로 모델을 학습(FIT) 합니다
model.fit(독립, 종속, epochs=100, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.7357
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 23.7711
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 23.1250
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8598
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 24.0630
Epoch 6/10
16/16 [==============================] - 0s 995us/step - loss: 24.0514
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 23.5673
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 23.4983
Epoch 9/10
16/16 [==============================] - 0s 983us/step - loss: 23.5821
Epoch 10/10
16/16 [==============================] - 0s 970us/step - loss: 23.8476


In [ ]:
# 4. 모델을 이용합니다
model.predict(독립[5:10])

array([[25.872238],
       [22.551044],
       [19.566368],
       [11.418421],
       [18.89872 ]], dtype=float32)

In [ ]:
종속[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [ ]:
# 모델의 수식 확인
model.get_weights()

[array([[-0.09422136],
        [ 0.04784127],
        [-0.01704179],
        [ 2.6358259 ],
        [-3.502867  ],
        [ 5.1613526 ],
        [-0.00871709],
        [-1.1002464 ],
        [ 0.20626107],
        [-0.01016019],
        [-0.55153745],
        [ 0.01353967],
        [-0.46674722]], dtype=float32), array([10.556653], dtype=float32)]

집값 = -0.09422136 * x1 + 0.04784127 * x2 + -0.01704179 * x3 + 
2.6358259 * x4 + -3.502867 * x5 + 5.1613526 * x6 + -0.00871709 * x7 +
-1.1002464 * x8 + 0.20626107 * x9 + -0.01016019 * x10 + 
-0.55153745 * x11 + 0.01353967 * x12 + -0.46674722 * x13 +
10.556653